# nodepool.yaml
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
spec:
  template:
    metadata:
      labels:
        role: general-worker
    spec:
      nodeClassRef:
        group: eks.amazonaws.com
        kind: NodeClass
        name: default

      requirements:
        # Explicitly exclude m5 instances
        - key: "eks.amazonaws.com/instance-family"
          operator: NotIn
          values: ["m5", "m5a", "m5n"]
        # Force t3 instances only
        - key: "eks.amazonaws.com/instance-family"
          operator: In
          values: ["t3"]
        - key: "node.kubernetes.io/instance-type"
          operator: In
          values: ["t3.small", "t3.medium"]
        - key: "topology.kubernetes.io/zone"
          operator: In
          values: ["us-east-1a", "us-east-1b"]
        - key: "kubernetes.io/arch"
          operator: In
          values: ["amd64"]
        - key: "karpenter.sh/capacity-type"
          operator: In
          values: ["on-demand"]

  limits:
    cpu: "4"
    memory: 16Gi