# cluster.yaml
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eks-auto-starter
  region: us-east-1
  version: "1.30"

autoModeConfig:
  enabled: true
  nodePools: 
    - general-purpose

vpc:
  cidr: "192.168.0.0/16"
  nat:
    gateway: Single

iam:
  withOIDC: true